<script setup lang="ts">
import { computed, ref } from 'vue'
import { useLocale } from '../composables/useLocale'
import { imageList } from '../utils/image'
const { isEn } = useLocale()
const boundary = ref<'none' | 'box' | 'wrapper'>('box')
const modes = computed(() => isEn.value ? [{ value: 'none', title: 'No constraint' }, { value: 'box', title: 'Cover the crop box' }, { value: 'wrapper', title: 'Cover the workspace' }] : [{ value: 'none', title: '无边界约束' }, { value: 'box', title: '覆盖裁剪框' }, { value: 'wrapper', title: '覆盖整个容器' }])
</script>
<template>
  <article class="concepts-page markdown-body">
    <h1>{{ isEn ? 'One image. Four concepts.' : '一张图片，四个关键概念。' }}</h1>
    <p>{{ isEn ? 'The workspace holds the image. The crop box selects part of it. Export turns that selection into a new image.' : '容器承载操作，图片在其中移动，裁剪框选取内容，导出把选区变成一张新图片。' }}</p>
    <h2 id="four-parts">{{ isEn ? 'Understand what you are editing' : '先看清，你在操作什么' }}</h2>
    <div class="concept-figure">
      <div class="diagram-workspace"><span class="diagram-label">01 · {{ isEn ? 'Workspace' : '容器' }}</span><img :src="imageList[4]" alt=""><div class="diagram-selection"><span>03 · {{ isEn ? 'Crop box' : '裁剪框' }}</span></div><span class="image-label">02 · {{ isEn ? 'Image' : '图片' }}</span></div>
      <span class="diagram-arrow">→</span><div class="diagram-output"><img :src="imageList[4]" alt=""><span>04 · {{ isEn ? 'Export' : '导出结果' }}</span></div>
    </div>
    <p class="figure-note">{{ isEn ? 'Concept illustration. Explore the live demos to see actual crop output.' : '概念示意图。实际选区和输出可以在功能示例中操作查看。' }}</p>
    <div class="concept-definitions"><div><code>wrapper</code><p>{{ isEn ? 'The size of the editing workspace.' : '编辑工作区的大小。' }}</p></div><div><code>img</code><p>{{ isEn ? 'The image you move, zoom, rotate or flip.' : '你可以移动、缩放、旋转或翻转的内容。' }}</p></div><div><code>cropLayout</code><p>{{ isEn ? 'The size of the selection, in workspace units.' : '选取区域的大小，使用容器坐标系。' }}</p></div><div><code>getCropBlob()</code><p>{{ isEn ? 'Generate an image file from the current selection.' : '把当前选区生成实际图片文件。' }}</p></div></div>
    <h2 id="layout-boundary">{{ isEn ? 'Initial layout and boundary coverage' : '初始布局，与持续的边界约束' }}</h2>
    <p>{{ isEn ? 'mode chooses the initial image layout. centerBox and centerWrapper control what must remain covered after interaction. These are different responsibilities.' : 'mode 决定图片最初怎样摆放；centerBox 和 centerWrapper 决定交互后图片必须覆盖哪里。它们承担不同的职责。' }}</p>
    <div class="boundary-options"><button v-for="mode in modes" :key="mode.value" type="button" :aria-pressed="boundary === mode.value" @click="boundary = mode.value as typeof boundary">{{ mode.title }}</button></div>
    <div class="boundary-figure" :class="`boundary-${boundary}`"><div class="boundary-image"><img :src="imageList[4]" alt=""></div><div class="boundary-selection"></div><span>{{ isEn ? 'WORKSPACE' : '容器' }}</span></div>
    <p v-if="boundary === 'none'">{{ isEn ? 'With both boundary props off, the selection may extend beyond the image.' : '两个边界参数都关闭时，选区可能露出图片外部。' }}</p>
    <p v-else-if="boundary === 'box'"><code>centerBox</code> — {{ isEn ? 'Keep the crop box covered by the image, useful for avatars and covers.' : '要求图片覆盖裁剪框，适合头像和封面。' }}</p>
    <p v-else><code>centerWrapper</code> — {{ isEn ? 'Keep the whole workspace covered by the image. This does not mean fitting the image inside the workspace.' : '要求图片覆盖整个容器，不是把整张图片缩小放进容器。' }}</p>
    <blockquote>{{ isEn ? 'The illustration compares the target relationships. During dragging, the existing component applies resistance and then rebounds after interaction. If both boundary props are enabled, crop-box coverage takes priority.' : '图示对比的是目标覆盖关系。实际拖动过程有越界阻力，交互结束后会回弹。两个参数同时开启时，优先使用裁剪框覆盖规则。' }}</blockquote>
    <router-link to="/demo-img">{{ isEn ? 'Try boundary control' : '实际操作边界控制' }} →</router-link>
    <h2 id="ratio-size">{{ isEn ? 'Resizing and aspect ratio are separate' : '允许缩放，不等于启用比例限制' }}</h2>
    <div class="concept-steps"><div><span>01</span><h3>{{ isEn ? 'Resize' : '允许调整选区' }}</h3><code>cropBoxResizable</code><p>{{ isEn ? 'Expose handles to resize the box. Off by default.' : '显示四边与四角控制点，默认关闭。' }}</p></div><div><span>02</span><h3>{{ isEn ? 'Enable constraints' : '启用比例与尺寸约束' }}</h3><code>cropBoxConstraintsEnabled</code><p>{{ isEn ? 'Apply the configured ratio and min/max sizes. Off by default.' : '让配置的宽高比与尺寸上下限生效，默认关闭。' }}</p></div><div><span>03</span><h3>{{ isEn ? 'Choose a ratio' : '设置需要的比例' }}</h3><code>cropAspectRatio = 16 / 9</code><p>{{ isEn ? 'Width divided by height. Constraints must be enabled.' : '宽度除以高度，需先启用约束。' }}</p></div></div>
    <p>{{ isEn ? 'Crop min/max sizes use workspace pixels. They do not specify export resolution. With constraints enabled, programmatic size changes follow the same ratio and size rules.' : '裁剪框最小/最大尺寸使用容器像素，不代表输出分辨率。开启约束后，程序化设置尺寸同样遵循当前比例和尺寸限制。' }}</p>
    <router-link to="/demo-crop">{{ isEn ? 'Try crop-box constraints' : '试试固定比例与尺寸限制' }} →</router-link>
    <h2 id="preview-export">{{ isEn ? 'Display size is not export resolution' : '看到的尺寸，不一定是导出的像素' }}</h2>
    <table><thead><tr><th>{{ isEn ? 'Setting' : '设置' }}</th><th>{{ isEn ? 'What it controls' : '它负责什么' }}</th></tr></thead><tbody><tr><td>outputType</td><td>{{ isEn ? 'Image format, such as PNG or WebP.' : '图片格式，例如 PNG、WebP。' }}</td></tr><tr><td>outputSize</td><td>{{ isEn ? 'Compression quality, not image width or height.' : '压缩质量，不是图片宽高。' }}</td></tr><tr><td>full</td><td>{{ isEn ? 'Use device pixel ratio for high-DPI export.' : '按设备像素比生成高分屏输出。' }}</td></tr><tr><td>original</td><td>{{ isEn ? 'Use source-image scale for the selected area.' : '按源图比例换算选区的输出尺寸。' }}</td></tr><tr><td>maxSideLength</td><td>{{ isEn ? 'Limit the longest exported edge.' : '限制导出结果的最长边像素。' }}</td></tr><tr><td>previewMaxSide</td><td>{{ isEn ? 'Preview rendering only; does not change export resolution.' : '仅影响预览渲染，不改变导出分辨率。' }}</td></tr></tbody></table>
    <p>{{ isEn ? 'For example, with original enabled, full disabled, and no max-edge clamp: a 200px selection at image scale 0.5 exports approximately 400px across.' : '例如开启 original、关闭 full，且未触发最长边限制时：显示宽 200px 的选区，图片缩放为 0.5，输出宽约为 400px。' }}</p>
    <router-link to="/demo-export">{{ isEn ? 'Compare real export results' : '对比实际导出结果' }} →</router-link>
    <h2 id="state-coordinates">{{ isEn ? 'Preview, state and source coordinates' : '预览、状态与源图坐标，各有用途' }}</h2>
    <ul><li><code>real-time</code> — {{ isEn ? 'Render a lightweight live preview from the provided image styles.' : '用事件提供的图片样式渲染轻量实时预览。' }}</li><li><code>change</code> — {{ isEn ? 'Observe image transforms and the crop box in workspace coordinates.' : '观察图片变换及容器坐标系中的裁剪框状态。' }}</li><li><code>getCropCoordinates()</code> — {{ isEn ? 'Read four selection corners in the orientation-normalized source image. Rotated corners and their bounding box are different shapes.' : '读取方向校正后源图中的四个选区角点。旋转后，角点组成的区域与轴对齐包围盒不同。' }}</li><li><code>getCropBlob()</code> — {{ isEn ? 'Export when needed; no need to export on every preview update.' : '按需导出，无需在每次预览更新时重复调用。' }}</li></ul>
  </article>
</template>
<style scoped>
.concept-figure { display:flex; align-items:center; justify-content:center; gap:28px; padding:30px 24px; border:1px solid var(--doc-line); border-radius:8px; background:#eaf0e3; }
.diagram-workspace { width:280px; height:195px; position:relative; background:#cfdcc8; padding:28px; border:1px dashed #8d9f81; }
.diagram-workspace > img { width:100%; height:100%; object-fit:cover; }.diagram-label { position:absolute; top:7px; left:10px; font-size: 12px; color:#405c38; }.image-label { position:absolute; bottom:6px; left:28px; font-size: 12px; }.diagram-selection { position:absolute; top:53px; left:81px; height:91px; width:122px; border:2px solid white; box-shadow:0 0 0 12px #203d2722; }.diagram-selection span { position:absolute; bottom:4px; left:5px; color:white; background:#173627c9; padding:4px; font-size: 12px; }.diagram-output img { width:100px; height:100px; object-fit:cover; display:block; border-radius:4px; }.diagram-output span { display:block; font-size: 12px; margin-top:12px; text-align:center; }.diagram-arrow { color:var(--doc-green); }.figure-note { font-size:12px; color:var(--doc-muted); }.concept-definitions { display:grid; grid-template-columns:1fr 1fr; gap:18px; margin:25px 0; }.concept-definitions > div { border-bottom:1px solid var(--doc-line); padding:10px 0; }.concept-definitions p { font-size:13px; color:var(--doc-muted); }.boundary-options { display:flex; flex-wrap:wrap; gap:8px; margin:20px 0; }.boundary-options button { border:1px solid var(--doc-line); background:white; border-radius:5px; padding:10px 12px; font-size:12px; }.boundary-options [aria-pressed=true] { background:var(--doc-green); color:white; border-color:var(--doc-green); }.boundary-figure { height:230px; position:relative; overflow:hidden; border:1px dashed #8d9f81; background:#e3ebda; border-radius:6px; }.boundary-image { position:absolute; left:24%; top:10%; width:53%; height:80%; transition:all .2s; }.boundary-image img { width:100%; height:100%; object-fit:cover; }.boundary-selection { position:absolute; width:38%; height:65%; top:17.5%; left:31%; border:2px solid white; box-shadow:0 0 0 1px #355d36; }.boundary-figure > span { position:absolute; top:10px; left:12px; padding:4px 7px; background:#f7f8f4d9; font-size: 12px; }.boundary-none .boundary-image { left:8%; width:45%; height:65%; }.boundary-wrapper .boundary-image { top:0;left:0;width:100%;height:100%; }.concept-steps { display:grid; grid-template-columns:1fr; gap:15px; margin:24px 0; }.concept-steps > div { padding:20px; border:1px solid var(--doc-line); border-radius:6px; }.concept-steps span { float:right; font:12px var(--doc-mono); color:var(--doc-muted); }.concept-steps h3 { margin:0 0 12px; font-size:16px; }.concept-steps p { font-size:13px; margin-bottom:0; }
@media(max-width:600px) { .concept-figure{gap:12px;padding:20px 12px;flex-wrap:wrap}.diagram-workspace{width:100%;max-width:280px}.diagram-output img{width:80px;height:80px}.concept-definitions{grid-template-columns:1fr}.concept-steps code{font-size: 12px} }
</style>
